export const FETCH_SERVERPORTS = "FETCH_SERVERPORTS";
export const NEW_SERVERPORT = "NEW_SERVERPORT";
export const FETCH_SERVERPORT_FOR_EDIT = "FETCH_SERVERPORT_FOR_EDIT";
export const EDIT_SERVERPORT = "EDIT_SERVERPORT";
export const DELETE_SERVERPORT = "DELETE_SERVERPORT";
